language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true
env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="
addons:
  apt:
    packages:
    - git

before_install: 
  - chmod +x before_install.sh
  - . ./before_install.sh

install: 
  - chmod +x install.sh
  - . ./install.sh
  - chmod +x run.sh

script: 
  - ./run.sh eg1 benchmark testmodel
  - ./run.sh eg3 benchmark testmodel
  - ./run.sh eg5 benchmark testmodel
  - ./run.sh eg6 benchmark testmodel
  - ./run.sh eg7 benchmark testmodel
  - ./run.sh NC benchmark testmodel
  - ./run.sh MCH benchmark testmodel
  - ./run.sh solvent_hexane benchmark testmodel
  - ./run.sh methane benchmark testmodel
  - chmod +x install_benchmark2.sh
  - . ./install_benchmark2.sh
  - ./run.sh eg1 benchmark2 testmodel2
  - ./run.sh eg3 benchmark2 testmodel2
  - ./run.sh eg5 benchmark2 testmodel2
  - ./run.sh eg6 benchmark2 testmodel2
  - ./run.sh eg7 benchmark2 testmodel2
  - ./run.sh NC benchmark2 testmodel2
  - ./run.sh MCH benchmark2 testmodel2
  - ./run.sh solvent_hexane benchmark2 testmodel2
  - ./run.sh methane benchmark2 testmodel2

after_script:
  - chmod +x after_install.sh
  - . ./after_install.sh
  
cache:
  pip: true
  apt: true
  # directories:
  #   - $HOME/anaconda/pkgs

branches:
  only:
    - /^rmgpy-.*$/
    - /^rmgdb-.*$/